services:
  baserow:
    image: docker.io/baserow/baserow:2.0.3
    restart: always
    environment:
      BASEROW_PUBLIC_URL: "http://localhost:8080"
    volumes:
      - baserow_data:/baserow/data
    ports:
      - target: 80
        published: 8080
      - target: 443
        published: 8443

volumes:
  baserow_data:
